//====================================================================================================
// Base code generated with Vector: WFA Gen (Build 2.0.4906.28604)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Serena Yeoh at ALIENWARE on 06/20/2013 17:43:50 
//====================================================================================================

using System;
using System.Activities;
using System.Collections.Generic;
using LeaveSample.Entities;
using LeaveSample.Business;

namespace LeaveSample.Workflows.Activities
{
    /// <summary>
    /// Cancel workflow activity.
    /// </summary>
    [Serializable]
    public sealed class Cancel : CodeActivity
    {
        // Argument declaration.
        public InOutArgument<Leave> Leave { get; set; }

        protected override void Execute(CodeActivityContext context)
        {

            // Argument initialization (if any).
            Leave leave = context.GetValue(this.Leave);

            // Instantiate business components.
            LeaveComponent leaveComponent = new LeaveComponent();

            // Call business component methods.
            leave = leaveComponent.Cancel(leave);

            // Set value to Out arguments (if any).
            context.SetValue(this.Leave, leave);
        }
    }
}
