//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.4877.28463)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Serena Yeoh at ALIENWARE on 05/22/2013 10:21:01 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;


namespace LeaveSample.Entities
{
    /// <summary>
    /// Represents a row of Leave data.
    /// </summary>
    [DataContract]
    public partial class Leave
    {
        public Leave()
        {
        }

        /// <summary>
        /// Gets or sets a long value for the LeaveID column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public long LeaveID { get; set; }

        /// <summary>
        /// Gets or sets a Guid value for the CorrelationID column.
        /// </summary>
        [DataMember]
        public Guid CorrelationID { get; set; }

        /// <summary>
        /// Gets or sets a byte value for the Category column.
        /// </summary>
        [DataMember]
        public LeaveCategories Category { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Employee column.
        /// </summary>
        [DataMember]
        public string Employee { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the StartDate column.
        /// </summary>
        [DataMember]
        [Required]
        public DateTime StartDate { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the EndDate column.
        /// </summary>
        [DataMember]
        [Required]
        public DateTime EndDate { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Description column.
        /// </summary>
        [DataMember]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets a byte value for the Duration column.
        /// </summary>
        [DataMember]
        [Required]
        [Range(1, 90)]
        public byte Duration { get; set; }

        /// <summary>
        /// Gets or sets a byte value for the Status column.
        /// </summary>
        [DataMember]
        public LeaveStatuses Status { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the IsCompleted column.
        /// </summary>
        [DataMember]
        public bool IsCompleted { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Remarks column.
        /// </summary>
        [DataMember]
        public string Remarks { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the DateSubmitted column.
        /// </summary>
        [DataMember]
        public DateTime DateSubmitted { get; set; }


    }
}
