//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.4841.16572)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Serena Yeoh at ALIENWARE on 05/08/2013 11:05:57 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace LeaveSample.Entities
{
    /// <summary>
    /// Represents a row of LeaveStatusLog data.
    /// </summary>
    [DataContract]
    public partial class LeaveStatusLog
    {
        /// <summary>
        /// Gets or sets a long value for the LogID column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public long LogID { get; set; }

        /// <summary>
        /// Gets or sets a long value for the LeaveID column.
        /// </summary>
        [DataMember]
        public long LeaveID { get; set; }

        /// <summary>
        /// Gets or sets a byte value for the Status column.
        /// </summary>
        [DataMember]
        public LeaveStatuses Status { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the Date column.
        /// </summary>
        [DataMember]
        public DateTime Date { get; set; }

    }
}
