//====================================================================================================
// Base code generated with Vector: WFA Gen (Build 2.0.4906.28604)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Serena Yeoh at ALIENWARE on 06/20/2013 17:49:28 
//====================================================================================================

using System;
using System.Activities;
using System.Activities.Presentation.Metadata;
using System.ComponentModel;
using System.Windows;
using System.Collections.Generic;
using LeaveSample.Entities;
using LeaveSample.Workflows.Activities;

namespace LeaveSample.Workflows.Designers
{
    /// <summary>
    /// Designer class for Reject.
    /// </summary>
    public partial class RejectDesigner : IRegisterMetadata
    {
        public RejectDesigner()
        {
            InitializeComponent();
        }

        public void Register()
        {
            AttributeTableBuilder builder = new AttributeTableBuilder();

            builder.AddCustomAttributes(typeof(Reject), new Attribute[] {
            new DesignerAttribute(typeof(RejectDesigner))});

            MetadataStore.AddAttributeTable(builder.CreateTable());
        }

        public void leaveEntry_Loaded(object sender, RoutedEventArgs e)
        {
            leaveEntry.ExpressionType = typeof(Leave);
        }

    }
}

