//====================================================================================================
// Base code generated with Velocity: SL Gen (Build 2.4.4841.16573)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Serena Yeoh at ALIENWARE on 05/09/2013 14:49:48 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ServiceModel;
using LeaveSample.Entities;

namespace LeaveSample.Services.Contracts
{
    /// <summary>
    /// Service contract for LeaveService.
    /// </summary>
    [ServiceContract]
    public interface ILeaveService
    {
        [OperationContract]
        List<LeaveStatusLog> ListLogsByLeave(long leaveID);

        [OperationContract]
        Leave GetLeaveById(long leaveID);

        [OperationContract]
        List<Leave> ListLeavesByEmployee(int maximumRows, int startRowIndex, 
            string sortExpression, string employee, LeaveCategories? category, 
            LeaveStatuses? status, out int totalRowCount);
    }
}
