//====================================================================================================
// Base code generated with Vector: WFA Gen (Build 2.0.4906.28604)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Serena Yeoh at ALIENWARE on 06/20/2013 17:49:28 
//====================================================================================================

using System;
using System.Activities;
using System.Activities.Presentation;
using System.Activities.Statements;
using System.Net.Security;
using System.ServiceModel.Activities;
using System.Windows;
using System.Collections.Generic;
using LeaveSample.Entities;
using LeaveSample.Business;

namespace LeaveSample.Workflows.Activities
{
    /// <summary>
    /// Messaging wrapper activity for Approve.
    /// </summary>
    /// <remarks>
    /// This class serves only as a convenience to simplify workflow services creation at
    /// design time. It does not contribute any functionality to running code.
    /// </remarks>
    public class ApproveReceiveSend : MessagingWrapperActivity, IActivityTemplateFactory
    {
        public Activity Create(DependencyObject target)
        {
            // Sequence container.
            var sequence = new Sequence();
            sequence.DisplayName = "Approve";

            // Correlation Handle.
            var handle = new Variable<CorrelationHandle>("_handle");
            var leave = new Variable<Leave>("_leave");

            // Get variable collection.
            var variables = GetVariableCollection(target);

            if (variables == null)
            {
                sequence.Variables.Add(handle);
                sequence.Variables.Add(leave);
            }
            else
            {
                handle = AddVariable<CorrelationHandle>(variables, handle);
                leave = AddVariable<Leave>(variables, leave);
            }

            // Create Receive Activity.
            var receive = new Receive();
            receive.DisplayName = "Approve Receive";
            receive.Action = "http://tempuri.org/ILeaveWorkflowService/Approve";
            receive.OperationName = "Approve";
            receive.ProtectionLevel = ProtectionLevel.None;
            receive.ServiceContractName = "ILeaveWorkflowService";

            // Add parameters to Receive
            var parameters = new ReceiveParametersContent();
            parameters.Parameters.Add("leave", new OutArgument<Leave>(leave));
            receive.Content = parameters;

            // Add CorrelationInitializer to Receive
            var initializer = new RequestReplyCorrelationInitializer();
            initializer.CorrelationHandle = new InArgument<CorrelationHandle>(handle);
            receive.CorrelationInitializers.Add(initializer);

            // Create SendReply Activity
            var send = new SendReply();
            send.DisplayName = "Approve Reply";
            send.Action = "http://tempuri.org/ILeaveWorkflowService/ApproveResponse";
            send.Request = receive;
            send.PersistBeforeSend = true;

            // Add parameters to SendReply
            var sendParameters = new SendParametersContent();
            sendParameters.Parameters.Add("ApproveResponseResult", new InArgument<Leave>(leave));
            send.Content = sendParameters;

            // Create Approve activity.
            Approve approve = new Approve();
            approve.DisplayName = "Approve";
            approve.Leave = leave;

            // Add activities to sequence.
            sequence.Activities.Add(receive);
            sequence.Activities.Add(approve);
            sequence.Activities.Add(send);

            return sequence;
        }
    }
}

